// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnuqluofutrzeigqtdju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudXFsdW9mdXRyemVpZ3F0ZGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNDE1MzUsImV4cCI6MjA1MTcxNzUzNX0.uTN6_df0o5_zVuiZ3fGD63FMGfQp4D4tmIsSdnnoNmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);